Update build.yml
Alter to require successful make build before pull request creation.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -18,3 +18,10 @@ jobs:
 
     - name: Build
       run: make
+
+    - name: Verify Build
+      run: |
+        if ! make; then
+          echo "Build failed"
+          exit 1
+        fi
